export const PRODUCTS_DATA = {
	cassis: {
		id: 'cassis',
		displayName: 'Cassis',
		productImage: '',
		bgColor: 'bg-brand-purple',
		videoUrlMp4: '/video/cassis-video.mp4',
		videoUrlWebm: '/video/cassis-video.webm',
	},
	passionFruit: {
		id: 'passionFruit',
		displayName: 'Passionfruit',
		productImage: '',
		bgColor: 'bg-brand-yellow',
		videoUrlMp4: '/video/passionFruit-video.mp4',
		videoUrlWebm: '/video/passionFruit-video.webm',
	},
	orange: {
		id: 'orange',
		displayName: 'Orange & Mandarin',
		productImage: '',
		bgColor: 'bg-brand-orange',
		videoUrlMp4: '/video/orange-video.mp4',
		videoUrlWebm: '/video/orange-video.webm',
	},
	lime: {
		id: 'lime',
		displayName: 'Rasberry & Lime',
		productImage: '',
		bgColor: 'bg-brand-green',
		videoUrlMp4: '/video/lime-video.mp4',
		videoUrlWebm: '/video/lime-video.webm',
	},
	grapefruit: {
		id: 'grapefruit',
		displayName: 'Grapefruit',
		productImage: '',
		bgColor: 'bg-brand-pink',
		videoUrlMp4: '/video/grapefruit-video.mp4',
		videoUrlWebm: '/video/grapefruit-video.webm',
	},
	lemon: {
		id: 'lemon',
		displayName: 'Lemon',
		productImage: '',
		bgColor: 'bg-brand-blue',
		videoUrlMp4: '/video/lemon-video.mp4',
		videoUrlWebm: '/video/lemon-video.webm',
	},
};
